# This is a basic workflow to help you get started with Actions
name: Verify CHANGELOG + Version

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  verify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: echo pwd
      run: echo $(pwd)

    - name: ls
      run: |
        echo $(pwd)
        ls
        echo "Event path is: $GITHUB_EVENT_PATH"
      # Runs a single command using the runners shell
    - name: store version
      run:  echo "::set-env name=MODULE_VERSION::$(head -n 1 VERSION)"

    - name: echo version
      run: echo "Version is $MODULE_VERSION"


