# This is a basic workflow to help you get started with Actions
name: Publish release

on:
  push:
    branches: [ master ]

jobs:
  publish_tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch tags
      run: git fetch -t -q

    - name: Create tag if missing
      id: create_if_missing
      run:  |
        MODULE_VERSION=$(head -n 1 VERSION)
        MODULE_NAME=$GITHUB_REPOSITORY
        if git rev-parse $MODULE_VERSION >/dev/null 2>&1; then
          echo "tag: $MODULE_VERSION already exists, nothing to do.";
          echo "::set-env name=CREATE::false"
        else
          echo "tag: $MODULE_VERSION does not exist, creating..."
          git tag $MODULE_VERSION
          git push origin $MODULE_VERSION
          echo "::set-env name=CREATE::true"
        fi
      
        echo "::set-env name=VERSION::$MODULE_VERSION"
        echo "::set-env name=REPO_NAME::$MODULE_NAME"

    - name: Slack notification
      if: env.CREATE == 'true'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      uses: Ilshidur/action-slack@fb92a78
      with:
        args: "A new version of ${{ env.REPO_NAME }} has been published ${{ env.VERSION }}" # Optional
    
    - name: Job has failed
      uses: Ilshidur/action-slack@fb92a78
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: 'The job has failed'

