# This is a basic workflow to help you get started with Actions
name: Publish releases

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish_tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch -t -q

    - name: Verify tags
      run:  |
        MODULE_VERSION=$(head -n 1 VERSION)
        echo "Version is $MODULE_VERSION"
        # Get remote tags

        if git rev-parse $MODULE_VERSION >/dev/null 2>&1; then
          echo "tag: $MODULE_VERSION already exists, nothing to do.";
        else
          echo "tag: $MODULE_VERSION does not exist, creating..."
          git tag $MODULE_VERSION
          git push origin $MODULE_VERSION

          # Notify slack
        fi

