name: Verify that VERSION is updated

on:
  pull_request:
    branches: [ master ]

jobs:
  check_that_version_file_is_updated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    # compare what files have changed 
    - name: list changed files
      run: |
        git fetch -q origin ${{ github.base_ref }}
        list=$(git diff origin/${{ github.base_ref }} --name-only)
        changes=$(echo $list | grep .tf | wc -l)
        if [ "$changes" -eq "0" ]
        then 
          echo "No terraform changes!"
        else
          echo "Terraform changed"
          version_changed=$(echo $list | grep VERSION | wc -l)
          if [ "$version_changed" -eq "0" ]
          then
            echo "[ERROR] *.tf files modified but VERSION didnt change"
            exit 1
          fi
        fi
