# This is a basic workflow to help you get started with Actions
name: Verify version is updated

#on: push
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Compare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: print env
      run: env
    # compare what files have changed 
    - name: list changed files
      run: |
        #git ls-tree --name-only -r ${GITHUB_REF##*/}
        git fetch ${{ github.base_ref }}
    - name: store version
      run:  |
        MODULE_VERSION=$(head -n 1 VERSION)
        echo "Version is $MODULE_VERSION"

